[build]
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/telegram"
  to = "/.netlify/functions/telegram-webhook"
  status = 200
